### ISSUE TITLE
dep(superchain-registry): Rust bindings

### ISSUE THREAD

**Issue by clabby** [ethereum-optimism/kona#193]
## Overview

The [`superchain-registry`](https://github.com/ethereum-optimism/superchain-registry) functions as a central location to declare protocol upgrade timestamps, contract deployments, etc. We should add Rust bindings for it. Being able to pull these in will be very beneficial for the `host` program, and ideally, projects like `op-reth` should use it as well.

**Comment by clabby** [comment]
@merklefruit - any chance this is interesting to you?

**Comment by merklefruit** [comment]
Yes absolutely! 🫡 
Will take a look shortly
