### ISSUE TITLE
feat: Kona Execution Extension

### ISSUE THREAD

**Issue by refcell** [ethereum-optimism/kona#211]
**Description**

Build an execution extension in upstream [reth](https://github.com/paradigmxyz/reth) that validates the generated payload attributes from `kona-derive`.

The execution extension should live in reth's [`exex examples`](https://github.com/paradigmxyz/reth/tree/main/examples/exex) directory. It should accept the committed L1 Blocks and run the derivation pipeline over these blocks, producing payload attributes. With the generated payload attributes, it should query the engine api for the payload from a trusted node and compare the derived attributes. Comparing these values validates that `kona-derive` successfully and correctly built attributes.

Future work should include execution, block hashing, and validation with the trusted sequencer to effectively create a consensus client that follows the safe head. This client could be further extended to track the unsafe head by supporting peer connections, an rpc server, etc etc - comprising a feature-complete alternative to the `op-node` rollup or consensus client.

**Comment by GrapeBaBa** [comment]
@refcell @clabby I would like to take this one, I saw an ongoing PR in reth, how to promote this and add new features？

**Comment by refcell** [comment]
This is now in https://github.com/paradigmxyz/op-rs
