### ISSUE TITLE
feat(client): Upstream Chain ID Rollup Config Mapping to SCR

### ISSUE THREAD

**Issue by refcell** [ethereum-optimism/kona#261]
**Description**

Upstream the [`rollup_config_from_chain_id`][cfg] function to the [`superchain-bindings`][scb] crate.

Currently, chain `RollupConfig` instances are `const` definitions in the [`superchain-primitives`][scp] crate.
These `const` definitions should be deleted. A mapping from chain id to `RollupConfig` definition for that chain should be crated in the `superchain-bindings` crate that dynamically constructs the `RollupConfig`s for chains in the superchain.

[scp]: https://github.com/ethereum-optimism/superchain-registry/tree/main/bindings/rust-primitives
[scb]: https://github.com/ethereum-optimism/superchain-registry/tree/main/bindings/rust-bindings
[cfg]: https://github.com/ethereum-optimism/kona/blob/main/bin/programs/client/src/boot.rs#L98-L104

**Comment by sergerad** [comment]
@refcell happy to help if there is anything else to do for this. Or if you post any other good first issues, I will keep an eye out
