### ISSUE TITLE
fix(derive): Provider U64 Types

### ISSUE THREAD

**Issue by refcell** [ethereum-optimism/kona#366]
**Description**

Update provider methods to use Alloy's [U64](https://docs.rs/alloy-primitives/latest/alloy_primitives/aliases/type.U64.html) type which gracefully decodes an unsigned 64 bits with the `0x` prefix.

This will involve updating the parsing in the [alloy providers](https://github.com/ethereum-optimism/kona/blob/main/crates/derive/src/online/alloy_providers.rs#L279-L288) to use [`U64::from_str(...)`](https://docs.rs/alloy-primitives/latest/alloy_primitives/aliases/type.U64.html#impl-FromStr-for-Uint%3CBITS,+LIMBS%3E).

**Comment by duonghb53** [comment]
@refcell Can I get this one?
