### ISSUE TITLE
feat(derive): EngineQueue

### ISSUE THREAD

**Issue by clabby** [ethereum-optimism/kona#54]
## Overview

The Engine Queue stage of the derivation pipeline is responsible for taking the payload attributes generated in the payload attributes derivation stage and send them to the execution engine.

For the sake of this implementation, the engine queue should be abstracted over the destination of the execution payloads (engine queue is probably not the best name). The best way to do this is probably to have a typed function that takes in the payloads and processes them.

**References**
- [Engine Queue](https://specs.optimism.io/protocol/derivation.html#engine-queue) specification.

**Comment by refcell** [comment]
We shouldn't need this since attribute processing is application-specific. For example, the initial kona exex validation logic will just need to compare payload attributes. `kona-derive` is lower-level and shouldn't need to define how downstream applications consume generate payload attributes.
