### ISSUE TITLE
bug(preimage): Investigate oracle reader flakes

### ISSUE THREAD

**Issue by clabby** [ethereum-optimism/kona#76]
## Overview

The oracle reader tests flaked in this workflow: https://github.com/ethereum-optimism/kona/actions/runs/8541657676/job/23401491592

Investigate the failure and fix it. Pretty sure this is just a race condition in the tokio test, though we should expect that the pipe properly blocks.

**Comment by clabby** [comment]
Closed w/ #96

**Comment by refcell** [comment]
Just experienced this flake again locally. Re-opening so we investigate again.

**Comment by clabby** [comment]
Haven't seen these in a good while after the latest updates. Closing for now.
